version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - React_app_name=aman-prod
    ports:
      - "8081:80"
    #env_file:
      #- ./env   