FROM node:16-alpine as build
WORKDIR /app
ARG React_app_name
ENV React_app_name = $React_app_name
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
