version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
  
  react-app1:
    build: 
      context: .
      dockerfile: Dockerfile.dev



    #env_file:
      #- ./env   