version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
    environment:
      - React_app_name=aman-dev-1

  react-app1:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
    environment:
      - React_app_name=aman-dev-2
    #env_file:
      #- ./env   